// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#pragma region HEADER FILES
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#pragma endregion

#pragma region CONSTANTS
const char DEVICE_LOGIN_NAME[]  = "f38a6c08-1e97-45e7-9227-e9f11997afa6";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password
#pragma endregion

#pragma region METHOD DECLARATIONS
//Executes when value of wateringTime changes
void onWateringTimeChange();

//Exeutes when value of waterValveStatus changes
void onWaterValveStatusChange();
#pragma endregion

#pragma region VARIABLES TO SYNC WITH CLOUD

//Watering time in minutes
int wateringTime;

//Electromagnetic valve open<->close status
bool waterValveStatus;

#pragma endregion

//Property initialization
void initProperties(){
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(wateringTime, READWRITE, ON_CHANGE, onWateringTimeChange, 10);
  ArduinoCloud.addProperty(waterValveStatus, READWRITE, ON_CHANGE, onWaterValveStatusChange);
}

//WifiConnection handler object
WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
